{% set name = "findpython" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/findpython-{{ version }}.tar.gz
  sha256: 5064a30393c52efc8c6a35790c375b8b0005d6f74f1729035b4b42647347e13d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - findpython = "findpython.__main__:main"

requirements:
  host:
    - pip
    - python >=3.7
    - pdm-backend
  run:
    - packaging >=20
    - python >=3.7

test:
  imports:
    - findpython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/findpython/
  summary: A utility to find python versions on your system
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
