{% set name = "findpython" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/findpython-{{ version }}.tar.gz
  sha256: 0234e64ca2215a1977f4ed7c4b65d1571783888cc2a4a1f6a9d8e463687e8bc3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - findpython = "findpython.__main__:main"

requirements:
  host:
    - pip
    - python >=3.7
    - pdm-pep517
  run:
    - packaging >=20
    - python >=3.7

test:
  imports:
    - findpython
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/findpython/
  summary: A utility to find python versions on your system
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
