{% set name = "findpython" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/findpython-{{ version }}.tar.gz
  sha256: 5863ea55556d8aadc693481a14ac4f3624952719efc1c5591abb0b4a9e965c94

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - findpython = "findpython.__main__:main"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
  run:
    - packaging >=20
    - python >={{ python_min }}

test:
  imports:
    - findpython
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/findpython/
  summary: A utility to find python versions on your system
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
