{% set name = "findpython" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/findpython-{{ version }}.tar.gz
  sha256: e0c75ba9f35a7f9bb4423eb31bd17358cccf15761b6837317719177aeff46723

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - findpython = "findpython.__main__:main"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - pdm-backend
  run:
    - packaging >=20
    - python >={{ python_min }}

test:
  imports:
    - findpython
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/findpython/
  summary: A utility to find python versions on your system
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
